#print("hello world!")
szam1=int(input("Adj me egy számot: "))
szam2=int(input("Adj me egy szmásik számot: "))

print("Két szám összege: ",szam1+szam2)
print("Két szám különbsége: ",szam1-szam2)
print("Két szám szorzata: ",szam1*szam2)
print("Két szám hányadosa: ",szam1/szam2)
print("Két szám maradéka: ",szam1%szam2)
print("Két szám egész osztása: ",szam1//szam2)